### ISSUE TITLE
Missing LASreader class definition

### ISSUE THREAD

**Issue by mloskot** [PulseWaves/PulseWaves#2]
In the ```inc/pulsereader_las.hpp``` file, there is forward declaration of ```class LASreader```, but the complete definition of it seems to be missing form the project.

**Comment by rapidlasso** [comment]
Correct. This requires includes and libraries of LASlib of LAStools. I have added a compile switch HAVE_LASLIB to compile this without LAS 1.3/1.4 FWF support.
